### ISSUE TITLE
Deployment zeigt nur Keter Fehlermeldung an

### ISSUE THREAD

**Issue by nimec01** [fmidue/codeworld#25]
https://autotool.fmi.uni-due.de/codeworld zeigt aktuell nur einen Fehler an. 

Ich gehe man davon aus, dass in letzter Zeit etwas an der Keter-Config geändert wurde, was nun zu diesem Fehler führt.

@marcellussiegburg

**Comment by marcellussiegburg** [comment]
Ich glaube, ich habe den Build mit der falschen Keter-Config durchgeführt. Problematisch ist wohl insbesondere, dass dieser Teil hier: https://github.com/fmidue/codeworld/blob/78be7ef416ef49211cba08e4701145d107287f1f/build-docker.sh#L27-L44 Bestandteil des `docker-build.sh` ist, d.h. letztlich erfordert, dass `docker-build.sh` erneut aufgerufen werden muss, wenn sich nur die Config ändert. Letztlich sollte das wohl eher Bestandteil des `publish.sh` sein. (Dafür sind wohl noch weitere Anpassungen nötig, hauptsächlich, dass ein Aufruf von zweimal `publish.sh` hintereinander noch immer funktioniert.)

Temporär bin ich auf eine ältere Version gewechselt, um das Problem momentan zu beheben [weil scheinbar nicht richtig gecached wurde, und noch einmal kompiliert werden muss; dauert mindestens einen halben Arbeitstag]

**Comment by nimec01** [comment]
Würde es nicht reichen, diesen Teil ("Create bundle") einfach in die publish.sh zu verschieben? Der Part ist ja nicht wirklich abhängig vom eigentlichen Compilation-Prozess. Bzw. könnte ich dann noch schauen, ob sich das Updaten des Archivs noch vereinfachen lässt.

>Dafür sind wohl noch weitere Anpassungen nötig, hauptsächlich, dass ein Aufruf von zweimal publish.sh hintereinander noch immer funktioniert.

Was wäre denn da das Problem? Im Endeffekt wird ja nur die Keter-Config ins Archiv gepackt.

**Comment by marcellussiegburg** [comment]
Vielleicht passt es auch, aber `tar xf "$ARCHIVEPATH"` auszuführen, um danach alles wieder zu archivieren, klingt etwas wild. Insbesondere kann ich mir vorstellen, dass eine dann eventuell im Archiv schon vorhandene keter-File eine lokale dann möglicherweise überschreibt? Das sollte wohl verhindert werden.
