### ISSUE TITLE
Differing "Inspect syntax"

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/codeworld#6]
For a slight simplification of the program from #5, when clicking `Inspect` ...

The original CodeWorld site shows stuff like this:
![image](https://github.com/fmidue/codeworld/assets/5853832/12bb19a4-7eee-40cf-8615-e94af6c4625f)

while the mirror site shows stuff like this:
![image](https://github.com/fmidue/codeworld/assets/5853832/fa5219b6-8643-45f3-852c-7970a08a1afb)

I suspect that there is some "switch" that decides between "Math syntax" and "Haskell syntax", and that the mirror site uses "Math syntax" here even when in "Haskell mode".

**Comment by marcellussiegburg** [comment]
This issue will be gone when we finally get our DNS name. But in the meantime we should probably default to Haskell syntax (so it will be wrong for https://autotool.fmi.uni-due.de/codeworld).
@nimec01 Can you figure out which redirects require amendment?

**Comment by nimec01** [comment]
This diff here is the culprit: https://github.com/fmidue/codeworld/commit/d65a7c311cbb0fdb8d04e939c0db0eb2c513231e#diff-abd7686eb82a633a64458affaaec108837d1d549f83c241af262aa02b66202c2L1976
I did not include the `mode` in the URL. The debug part of `codeworld-api` hence did not know that this was generated using the Haskell mode.

```haskell
foreign import javascript unsafe "/\\bmode=haskell\\b/.test(location.search)"
    haskellMode :: Bool
```
I will open a pull request to fix that.

**Comment by jvoigtlaender** [comment]
I still see 
![image](https://github.com/fmidue/codeworld/assets/5853832/cfdd6f84-3122-41d6-b8be-4de295b3296d)
on https://autotool.fmi.uni-due.de/haskell

**Comment by nimec01** [comment]
The changes in #11 don't seem to be applied in this deployed version (no `mode` parameter in the iframe URL). It seems to me that only the library changes (#10) changes were applied. Perhaps a problem during deployment? @marcellussiegburg  The `web/` directory in the keter archive might be an old one. This would also explain why #8 is still a thing.

A look into the requested scripts indeed shows that the `web/` resources are old.
![image](https://github.com/fmidue/codeworld/assets/24428341/7a542cb2-ebdf-42a7-bee2-64f030b117bf)

**Comment by marcellussiegburg** [comment]
I redeployed CodeWorld. I am pretty sure this issue (and also #8 are gone now). To rule out caching or other weird stuff: @nimec01 Can you please confirm that the issue is gone (for good) now?

**Comment by nimec01** [comment]
> @nimec01 Can you please confirm that the issue is gone (for good) now?

Both the guide and the inspection now work as expected.
