### ISSUE TITLE
Task06, Task07, Task09, Task13, Task14, Task22, Task24 - no animation

### ISSUE THREAD

**Issue by mateuszcygan** [fmidue/codeworld#7]
**Shared Program**: 
https://autotool.fmi.uni-due.de/haskell#PXrNZLqwEkEDX8uGg7c0gsg
https://autotool.fmi.uni-due.de/haskell#PkI4IHL0h431KUvBOB_3tQQ
https://autotool.fmi.uni-due.de/haskell#POJV8ThMmp5g7m9qDRc3qPA
https://autotool.fmi.uni-due.de/haskell#PDKdXUNkW05Pt_Rg144Y7_g
https://autotool.fmi.uni-due.de/haskell#PYeyv4tJtSFhUlqEOfhDnqA
https://autotool.fmi.uni-due.de/haskell#Ph_wyWfkVc_VbIXtnePZSjw
https://autotool.fmi.uni-due.de/haskell#PZJ4ztzHsD_sIVR0gl7BNZg

**Description**
GoogleChrome, macOS

Code compiles, but animation doesn't appear after clicking the "Run" button
There are no "Inspect" (and "Share") buttons
<img width="1679" alt="Screenshot 2024-04-17 at 11 28 41" src="https://github.com/fmidue/codeworld/assets/75842464/5109afb9-dbee-4bb5-86d3-2440ae4ba9f0">

**Comment by marcellussiegburg** [comment]
@mateuszcygan Sharing links to programs does not work (as it does at the CodeWorld server). Programs are stored in the local browser cache (and thus are unavailable for others when clicking the link).

**Comment by marcellussiegburg** [comment]
I have increased buffer sizes. @mateuszcygan Can you please check back if this resolves the issue for all these tasks.

**Comment by mateuszcygan** [comment]
For Task14 and Task24, the animation is still not displayed

**Comment by marcellussiegburg** [comment]
I have increased the buffer size further. Both mentioned sample solutions are executable now.
