### ISSUE TITLE
Guide "Loading..."

### ISSUE THREAD

**Issue by mateuszcygan** [fmidue/codeworld#8]
**Shared Programme**
https://autotool.fmi.uni-due.de/haskell (Haskell version)
**Description**
The content of guide is not displayed (in each of the tabs), only "Loading..." displayed all the time
GoogleChrome, macOS
<img width="1141" alt="Screenshot 2024-04-17 at 11 47 24" src="https://github.com/fmidue/codeworld/assets/75842464/632fe07b-58b3-423c-bbf7-9535c2c5bf81">

**Comment by marcellussiegburg** [comment]
@nimec01 Do you know what is causing this? Are there missing redirects?

**Comment by nimec01** [comment]
It is possible that #4 introduced this problem. I will have a look at that.

**Comment by nimec01** [comment]
I found the culprit: The regex is a bit too strict (does not allow hyphens in the requested path). I will open a pull request to fix that.

**Comment by jvoigtlaender** [comment]
I still see this when opening the Guide:
![image](https://github.com/fmidue/codeworld/assets/5853832/601f108c-0dca-4793-af5c-a882039c36ef)
